set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/s_axis_tvalid]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/s_axis_tuser]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/s_axis_tlast]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tvalid]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tready]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tuser]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tlast]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/frame_sof_accept]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/image_tx_done]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/capture_enable]
set_property MARK_DEBUG true [get_nets qr_ip1_bd_i/qr_rgb565_gray8_axis_0/frame_slot_available]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list qr_ip1_bd_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/capture_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/frame_slot_available]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/frame_sof_accept]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/image_tx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tuser]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/m_img_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/s_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/s_axis_tuser]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list qr_ip1_bd_i/qr_rgb565_gray8_axis_0/s_axis_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 62500000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets qr_ip1_bd_i/processing_system7_0_FCLK_CLK0]
