`timescale 1 ns / 1 ps

/*
 * ============================================================================
 * Module : qr_runtime
 *
 * QR processing and frame-lifecycle IP wrapper
 *
 * Hierarchy
 *   qr_runtime
 *   ├─ qr_runtime_slave_lite_v1_0_S00_AXI : AXI4-Lite transport only
 *   ├─ qr_runtime_csr_core                      : CSR semantics
 *   ├─ qr_frame_completion_ctrl                 : Frame-aligned completion/ACK
 *   └─ qr_postprocess_runtime_core              : Functional QR runtime core
 *
 * Frame-aligned lifecycle
 *
 *   coordinated QR start (= ip2_start)
 *             |
 *             +---- result_tx_done -------------------+
 *             |                                       |
 *             +---- image_tx_done --------------------+
 *                                                     |
 *                                                     v
 *                                         frame_complete_pending
 *                                                     |
 *                                              PS CONTROL[6]
 *                                                 FRAME_ACK
 *                                                     |
 *                                                     v
 *                                              frame_complete
 *                                                     |
 *                                                     v
 *                                  qr_postprocess_runtime_core
 *                                      final_processing_done
 *                                                     |
 *                                                     v
 *                                       frontend_frame_release
 *
 * IMPORTANT
 *   The Gray8 stream is generated outside this IP. The system connects
 *   image_tx_done / image_frame_id / image_overflow_error to the capture
 *   and frame-control path. Keep those inputs paired with the result frame
 *   before acknowledging completion through the CSR interface.
 * ============================================================================
 */

module qr_runtime #(
    // -------------------------------------------------------------------------
    // QR runtime parameters
    // -------------------------------------------------------------------------
    parameter integer MAX_RECORDS           = 16,
    parameter integer EVENT_FIFO_DEPTH      = 32,
    parameter integer EVENT_FIFO_ADDR_WIDTH = 5,
    parameter integer FRAME_TIMEOUT_W       = 24,

    // -------------------------------------------------------------------------
    // AXI4-Lite parameters generated by Vivado
    // -------------------------------------------------------------------------
    parameter integer C_S00_AXI_DATA_WIDTH  = 32,
    parameter integer C_S00_AXI_ADDR_WIDTH  = 6
)(
    // =========================================================================
    // Clock / reset
    // =========================================================================
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 s00_axi_aclk CLK" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME s00_axi_aclk, ASSOCIATED_BUSIF S00_AXI:S_AXIS_EVENT:M_AXIS_RESULT, ASSOCIATED_RESET s00_axi_aresetn, FREQ_HZ 62500000" *)
    input  wire                         s00_axi_aclk,

    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 s00_axi_aresetn RST" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME s00_axi_aresetn, POLARITY ACTIVE_LOW" *)
    input  wire                         s00_axi_aresetn,

    // =========================================================================
    // AXI4-Lite Slave : S00_AXI
    // =========================================================================
    input  wire [C_S00_AXI_ADDR_WIDTH-1:0] s00_axi_awaddr,
    input  wire [2:0]                   s00_axi_awprot,
    input  wire                         s00_axi_awvalid,
    output wire                         s00_axi_awready,

    input  wire [C_S00_AXI_DATA_WIDTH-1:0] s00_axi_wdata,
    input  wire [(C_S00_AXI_DATA_WIDTH/8)-1:0] s00_axi_wstrb,
    input  wire                         s00_axi_wvalid,
    output wire                         s00_axi_wready,

    output wire [1:0]                   s00_axi_bresp,
    output wire                         s00_axi_bvalid,
    input  wire                         s00_axi_bready,

    input  wire [C_S00_AXI_ADDR_WIDTH-1:0] s00_axi_araddr,
    input  wire [2:0]                   s00_axi_arprot,
    input  wire                         s00_axi_arvalid,
    output wire                         s00_axi_arready,

    output wire [C_S00_AXI_DATA_WIDTH-1:0] s00_axi_rdata,
    output wire [1:0]                   s00_axi_rresp,
    output wire                         s00_axi_rvalid,
    input  wire                         s00_axi_rready,
    
    // =========================================================================
    input  wire                         frame_sof_accept,

    // =========================================================================
    // Event AXI4-Stream input from IP2
    // =========================================================================
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_EVENT TDATA" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S_AXIS_EVENT, TDATA_NUM_BYTES 4, HAS_TKEEP 1, HAS_TLAST 1, HAS_TREADY 1" *)
    input  wire [31:0]                  s_axis_event_tdata,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_EVENT TKEEP" *)
    input  wire [3:0]                   s_axis_event_tkeep,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_EVENT TVALID" *)
    input  wire                         s_axis_event_tvalid,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_EVENT TREADY" *)
    output wire                         s_axis_event_tready,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S_AXIS_EVENT TLAST" *)
    input  wire                         s_axis_event_tlast,

    // =========================================================================
    // QRP1 Result AXI4-Stream output
    // =========================================================================
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TDATA" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M_AXIS_RESULT, TDATA_NUM_BYTES 4, HAS_TKEEP 1, HAS_TLAST 1, HAS_TREADY 1" *)
    output wire [31:0]                  m_axis_result_tdata,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TKEEP" *)
    output wire [3:0]                   m_axis_result_tkeep,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TVALID" *)
    output wire                         m_axis_result_tvalid,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TREADY" *)
    input  wire                         m_axis_result_tready,

    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M_AXIS_RESULT TLAST" *)
    output wire                         m_axis_result_tlast,

    // =========================================================================
    // IP1 / frontend handshake
    // =========================================================================
    input  wire                         frontend_frame_ready,
    input  wire [7:0]                   frontend_valid_margin,

    output wire                         frontend_frame_release,
    output wire                         frontend_frame_stuck,
    output wire                         frontend_stat_clear,

    // =========================================================================
    // IP2 handshake / error inputs
    // =========================================================================
    output wire                         ip2_start,
    input  wire                         ip2_start_ready,
    input  wire                         ip2_processing_busy,
    input  wire                         ip2_processing_done,
    output wire                         ip2_error_clear,

    input  wire                         ip2_scan_vcc_error,
    input  wire                         ip2_candidate_overrun_error,
    input  wire                         ip2_candidate_drop_error,
    input  wire                         ip2_coordinate_error,
    input  wire                         ip2_arbiter_protocol_error,
    input  wire                         ip2_row_done_overrun_error,
    input  wire                         ip2_event_stability_error,
    input  wire                         ip2_event_row_order_error,
    input  wire                         ip2_event_protocol_error,

    input  wire                         external_fatal_frame_error,

    // =========================================================================
    // Frame-aligned image-side status
    //
    // These are supplied by the image-stream path for now.
    // =========================================================================
    input  wire                         image_tx_done,
    input  wire [31:0]                  image_frame_id,
    input  wire                         image_overflow_error,
    input  wire [15:0]                  frame_drop_count,
    input  wire [5:0]                   fe_mode_applied,

    /*
     * Persistent CSR CONTROL[5].
     * Connect this to the later image-stream/capture control block.
     */
    output wire                         image_capture_enable,

    // =========================================================================
    // Interrupt
    // =========================================================================
    (* X_INTERFACE_INFO = "xilinx.com:signal:interrupt:1.0 irq INTERRUPT" *)
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME irq, SENSITIVITY LEVEL_HIGH" *)
    output wire                         irq,

    // =========================================================================
    // Runtime / debug status
    // =========================================================================
    output wire [31:0]                  active_frame_id,
    output wire [31:0]                  next_frame_id,

    output wire [31:0]                  result_error_flags,
    output wire [15:0]                  result_word_length,
    output wire [15:0]                  result_byte_length,
    output wire [7:0]                   candidate_count,

    output wire                         result_ready,
    output wire                         processing_busy,
    output wire                         postprocess_done,
    output wire                         result_tx_done,

    output wire                         frame_complete_pending,
    output wire                         completion_protocol_error,
    output wire                         system_error,

    output wire [8:0]                   stored_hit_count,
    output wire [5:0]                   allocated_label_count,
    output wire [18:0]                  accumulated_hit_count,
    output wire [5:0]                   qualified_property_count
);

    // =========================================================================
    // Internal CSR bridge
    // =========================================================================

    wire                              csr_wr_en;
    wire [C_S00_AXI_ADDR_WIDTH-1:0]   csr_wr_addr;
    wire [31:0]                       csr_wr_data;
    wire [3:0]                        csr_wr_strb;

    wire [C_S00_AXI_ADDR_WIDTH-1:0]   csr_rd_addr;
    wire [31:0]                       csr_rd_data;

    // =========================================================================
    // CSR control outputs
    // =========================================================================

    wire        enable;
    wire        auto_start_enable;
    wire        manual_start_pulse;
    wire        soft_reset_pulse;
    wire        error_clear_pulse;
    wire        stream_start_pulse;
    wire        frame_ack_pulse;

    wire [31:0] frame_id_seed;
    wire        frame_id_seed_write;

    wire [31:0] irq_enable_unused;
    wire [31:0] irq_status_unused;

    // =========================================================================
    // Core / Frame-aligned status
    // =========================================================================

    wire feature_start_ready;
    wire core_frame_control_error;
    wire core_frame_id_protocol_error;
    wire core_system_error;

    wire frame_complete;
    wire image_done_seen_unused;
    wire result_done_seen_unused;

    wire runtime_combined_error;

    /*
     * qr_postprocess_axis_qrp1_core drives M_AXIS_RESULT TVALID during the
     * complete packet-send state, so this is equivalent to its stream_busy
     * status for the current QRP1 builder.
     */
    wire result_stream_busy;
    assign result_stream_busy = m_axis_result_tvalid;

    /*
     * CSR remains alive during a software soft-reset.
     * Functional runtime blocks are reset by this derived reset.
     */
    wire runtime_aresetn;
    assign runtime_aresetn =
        s00_axi_aresetn &&
        !soft_reset_pulse;

    /*
     * Include errors that live outside qr_postprocess_runtime_core in the
     * top-level combined-error status.
     */
    assign runtime_combined_error =
        core_system_error ||
        completion_protocol_error ||
        image_overflow_error ||
        external_fatal_frame_error;

    assign system_error =
        runtime_combined_error;

    // =========================================================================
    // 1) AXI4-Lite transport shell
    // =========================================================================

    qr_runtime_slave_lite_v1_0_S00_AXI #(
        .C_S_AXI_DATA_WIDTH (C_S00_AXI_DATA_WIDTH),
        .C_S_AXI_ADDR_WIDTH (C_S00_AXI_ADDR_WIDTH)
    ) u_s00_axi (
        .csr_wr_en       (csr_wr_en),
        .csr_wr_addr     (csr_wr_addr),
        .csr_wr_data     (csr_wr_data),
        .csr_wr_strb     (csr_wr_strb),

        .csr_rd_addr     (csr_rd_addr),
        .csr_rd_data     (csr_rd_data),

        .S_AXI_ACLK      (s00_axi_aclk),
        .S_AXI_ARESETN   (s00_axi_aresetn),

        .S_AXI_AWADDR    (s00_axi_awaddr),
        .S_AXI_AWPROT    (s00_axi_awprot),
        .S_AXI_AWVALID   (s00_axi_awvalid),
        .S_AXI_AWREADY   (s00_axi_awready),

        .S_AXI_WDATA     (s00_axi_wdata),
        .S_AXI_WSTRB     (s00_axi_wstrb),
        .S_AXI_WVALID    (s00_axi_wvalid),
        .S_AXI_WREADY    (s00_axi_wready),

        .S_AXI_BRESP     (s00_axi_bresp),
        .S_AXI_BVALID    (s00_axi_bvalid),
        .S_AXI_BREADY    (s00_axi_bready),

        .S_AXI_ARADDR    (s00_axi_araddr),
        .S_AXI_ARPROT    (s00_axi_arprot),
        .S_AXI_ARVALID   (s00_axi_arvalid),
        .S_AXI_ARREADY   (s00_axi_arready),

        .S_AXI_RDATA     (s00_axi_rdata),
        .S_AXI_RRESP     (s00_axi_rresp),
        .S_AXI_RVALID    (s00_axi_rvalid),
        .S_AXI_RREADY    (s00_axi_rready)
    );

    // =========================================================================
    // 2) CSR semantics
    // =========================================================================

    qr_runtime_csr_core #(
        .ADDR_W (C_S00_AXI_ADDR_WIDTH)
    ) u_csr (
        .aclk                    (s00_axi_aclk),
        .aresetn                 (s00_axi_aresetn),

        .wr_en                   (csr_wr_en),
        .wr_addr                 (csr_wr_addr),
        .wr_data                 (csr_wr_data),
        .wr_strb                 (csr_wr_strb),

        .rd_addr                 (csr_rd_addr),
        .rd_data                 (csr_rd_data),

        .processing_busy         (processing_busy),
        .feature_start_ready     (feature_start_ready),
        .frontend_frame_ready    (frontend_frame_ready),
        .result_ready            (result_ready),
        .stream_busy             (result_stream_busy),

        .packet_tx_done          (result_tx_done),
        .image_tx_done           (image_tx_done),

        .combined_error          (runtime_combined_error),
        .frame_stuck             (frontend_frame_stuck),
        .image_overflow_error    (image_overflow_error),
        .frame_id_protocol_error (core_frame_id_protocol_error),
        .frame_complete_pending  (frame_complete_pending),

        .result_word_length      (result_word_length),
        .candidate_count         (candidate_count),
        .error_flags             (result_error_flags),

        .active_frame_id         (active_frame_id),
        .image_frame_id          (image_frame_id),
        .frame_drop_count        (frame_drop_count),

        .fe_mode_applied         (fe_mode_applied),
        .valid_margin            (frontend_valid_margin[5:0]),

        .enable                  (enable),
        .image_capture_enable    (image_capture_enable),
        .auto_start_enable       (auto_start_enable),

        .manual_start_pulse      (manual_start_pulse),
        .soft_reset_pulse        (soft_reset_pulse),
        .error_clear_pulse       (error_clear_pulse),
        .stream_start_pulse      (stream_start_pulse),
        .frame_ack_pulse         (frame_ack_pulse),

        .frame_id_seed           (frame_id_seed),
        .frame_id_seed_write     (frame_id_seed_write),

        .irq_enable              (irq_enable_unused),
        .irq_status              (irq_status_unused),
        .irq                     (irq)
    );

    // =========================================================================
    // 3) Pure functional QR runtime core
    // =========================================================================

    qr_postprocess_runtime_core #(
        .MAX_RECORDS           (MAX_RECORDS),
        .EVENT_FIFO_DEPTH      (EVENT_FIFO_DEPTH),
        .EVENT_FIFO_ADDR_WIDTH (EVENT_FIFO_ADDR_WIDTH),
        .FRAME_TIMEOUT_W       (FRAME_TIMEOUT_W)
    ) u_runtime_core (
        .aclk                         (s00_axi_aclk),
        .aresetn                      (s00_axi_aresetn),

        .enable                       (enable),
        .auto_start_enable            (auto_start_enable),
        .manual_start_pulse           (manual_start_pulse),
        .soft_reset_pulse             (soft_reset_pulse),
        .error_clear_pulse            (error_clear_pulse),
        .stream_start_pulse           (stream_start_pulse),

        .frame_id_seed                (frame_id_seed),
        .frame_id_seed_write          (frame_id_seed_write),

        /*
         * Frame-aligned release occurs only after image + result + FRAME_ACK.
         */
        .final_processing_done        (frame_complete),
        .frame_sof_accept             (frame_sof_accept),

        .s_axis_event_tdata           (s_axis_event_tdata),
        .s_axis_event_tkeep           (s_axis_event_tkeep),
        .s_axis_event_tvalid          (s_axis_event_tvalid),
        .s_axis_event_tready          (s_axis_event_tready),
        .s_axis_event_tlast           (s_axis_event_tlast),

        .m_axis_result_tdata          (m_axis_result_tdata),
        .m_axis_result_tkeep          (m_axis_result_tkeep),
        .m_axis_result_tvalid         (m_axis_result_tvalid),
        .m_axis_result_tready         (m_axis_result_tready),
        .m_axis_result_tlast          (m_axis_result_tlast),

        .frontend_frame_ready         (frontend_frame_ready),
        .frontend_valid_margin        (frontend_valid_margin),

        .frontend_frame_release       (frontend_frame_release),
        .frontend_frame_stuck         (frontend_frame_stuck),
        .frontend_stat_clear          (frontend_stat_clear),

        .ip2_start                    (ip2_start),
        .ip2_start_ready              (ip2_start_ready),
        .ip2_processing_busy          (ip2_processing_busy),
        .ip2_processing_done          (ip2_processing_done),
        .ip2_error_clear              (ip2_error_clear),

        .ip2_scan_vcc_error           (ip2_scan_vcc_error),
        .ip2_candidate_overrun_error  (ip2_candidate_overrun_error),
        .ip2_candidate_drop_error     (ip2_candidate_drop_error),
        .ip2_coordinate_error         (ip2_coordinate_error),
        .ip2_arbiter_protocol_error   (ip2_arbiter_protocol_error),
        .ip2_row_done_overrun_error   (ip2_row_done_overrun_error),
        .ip2_event_stability_error    (ip2_event_stability_error),
        .ip2_event_row_order_error    (ip2_event_row_order_error),
        .ip2_event_protocol_error     (ip2_event_protocol_error),

        .external_fatal_frame_error   (external_fatal_frame_error),

        .feature_start_ready          (feature_start_ready),

        .active_frame_id              (active_frame_id),
        .next_frame_id                (next_frame_id),

        .result_error_flags           (result_error_flags),
        .result_word_length           (result_word_length),
        .result_byte_length           (result_byte_length),
        .candidate_count              (candidate_count),

        .result_ready                 (result_ready),
        .processing_busy              (processing_busy),
        .postprocess_done             (postprocess_done),
        .result_tx_done               (result_tx_done),

        .frame_control_error          (core_frame_control_error),
        .frame_id_protocol_error      (core_frame_id_protocol_error),
        .system_error                 (core_system_error),

        .stored_hit_count             (stored_hit_count),
        .allocated_label_count        (allocated_label_count),
        .accumulated_hit_count        (accumulated_hit_count),
        .qualified_property_count     (qualified_property_count)
    );

    // =========================================================================
    // 4) Frame-aligned completion controller
    // =========================================================================

    qr_frame_completion_ctrl u_frame_completion (
        .aclk                      (s00_axi_aclk),
        .aresetn                   (runtime_aresetn),

        /*
         * ip2_start is the coordinated one-shot start generated by the
         * functional runtime core.
         */
        .frame_start                (frame_sof_accept),

        .image_tx_done              (image_tx_done),
        .result_tx_done             (result_tx_done),

        .frame_ack_pulse            (frame_ack_pulse),
        .stat_clear                 (error_clear_pulse),

        .image_done_seen            (image_done_seen_unused),
        .result_done_seen           (result_done_seen_unused),
        .frame_complete_pending     (frame_complete_pending),
        .frame_complete             (frame_complete),
        .completion_protocol_error  (completion_protocol_error)
    );

endmodule
