
#ifndef VISION_FRONTEND_IP_H
#define VISION_FRONTEND_IP_H


/****************** Include Files ********************/
#include "xil_types.h"
#include "xstatus.h"

#define VISION_FRONTEND_IP_CTRL_OFFSET       0x00U
#define VISION_FRONTEND_IP_FE_MODE_OFFSET    0x04U
#define VISION_FRONTEND_IP_THRESH_OFFSET     0x08U
#define VISION_FRONTEND_IP_GEOM_OFFSET       0x0CU
#define VISION_FRONTEND_IP_STATUS_OFFSET     0x10U
#define VISION_FRONTEND_IP_FRAME_CNT_OFFSET  0x14U
#define VISION_FRONTEND_IP_FE_META_OFFSET    0x18U
#define VISION_FRONTEND_IP_VERSION_OFFSET    0x1CU

#define VISION_FRONTEND_IP_CTRL_ENABLE_MASK         0x00000001U
#define VISION_FRONTEND_IP_CTRL_SOFT_RESET_MASK     0x00000002U
#define VISION_FRONTEND_IP_CTRL_FRAME_RELEASE_MASK  0x00000004U
#define VISION_FRONTEND_IP_CTRL_FB_INV_MASK         0x00000008U
#define VISION_FRONTEND_IP_CTRL_STAT_CLEAR_MASK     0x00000010U

#define VISION_FRONTEND_IP_STATUS_BUSY_MASK           0x00000001U
#define VISION_FRONTEND_IP_STATUS_FRAME_READY_MASK    0x00000002U
#define VISION_FRONTEND_IP_STATUS_FRAME_DROPPED_MASK  0x00000004U
#define VISION_FRONTEND_IP_STATUS_CFG_INVALID_MASK    0x00000008U
#define VISION_FRONTEND_IP_STATUS_DMA_OVERFLOW_MASK   0x00000010U
#define VISION_FRONTEND_IP_STATUS_FRAME_STUCK_MASK    0x00000040U

#define VISION_FRONTEND_IP_VERSION_VALUE 0x00010000U

/* Backward-compatible aliases generated by the original AXI wizard. */
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG0_OFFSET VISION_FRONTEND_IP_CTRL_OFFSET
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG1_OFFSET VISION_FRONTEND_IP_FE_MODE_OFFSET
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG2_OFFSET VISION_FRONTEND_IP_THRESH_OFFSET
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG3_OFFSET VISION_FRONTEND_IP_GEOM_OFFSET
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG4_OFFSET VISION_FRONTEND_IP_STATUS_OFFSET
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG5_OFFSET VISION_FRONTEND_IP_FRAME_CNT_OFFSET
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG6_OFFSET VISION_FRONTEND_IP_FE_META_OFFSET
#define VISION_FRONTEND_IP_S00_AXI_SLV_REG7_OFFSET VISION_FRONTEND_IP_VERSION_OFFSET


/**************************** Type Definitions *****************************/
/**
 *
 * Write a value to a VISION_FRONTEND_IP register. A 32 bit write is performed.
 * If the component is implemented in a smaller width, only the least
 * significant data is written.
 *
 * @param   BaseAddress is the base address of the VISION_FRONTEND_IPdevice.
 * @param   RegOffset is the register offset from the base to write to.
 * @param   Data is the data written to the register.
 *
 * @return  None.
 *
 * @note
 * C-style signature:
 * 	void VISION_FRONTEND_IP_mWriteReg(u32 BaseAddress, unsigned RegOffset, u32 Data)
 *
 */
#define VISION_FRONTEND_IP_mWriteReg(BaseAddress, RegOffset, Data) \
  	Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))

/**
 *
 * Read a value from a VISION_FRONTEND_IP register. A 32 bit read is performed.
 * If the component is implemented in a smaller width, only the least
 * significant data is read from the register. The most significant data
 * will be read as 0.
 *
 * @param   BaseAddress is the base address of the VISION_FRONTEND_IP device.
 * @param   RegOffset is the register offset from the base to write to.
 *
 * @return  Data is the data from the register.
 *
 * @note
 * C-style signature:
 * 	u32 VISION_FRONTEND_IP_mReadReg(u32 BaseAddress, unsigned RegOffset)
 *
 */
#define VISION_FRONTEND_IP_mReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))

/************************** Function Prototypes ****************************/
/**
 *
 * Run a self-test on the driver/device. Note this may be a destructive test if
 * resets of the device are performed.
 *
 * If the hardware system is not built correctly, this function may never
 * return to the caller.
 *
 * @param   baseaddr_p is the base address of the VISION_FRONTEND_IP instance to be worked on.
 *
 * @return
 *
 *    - XST_SUCCESS   if all self-test code passed
 *    - XST_FAILURE   if any self-test code failed
 *
 * @note    Caching must be turned off for this function to work.
 * @note    Self test may fail if data memory and device are not on the same bus.
 *
 */
XStatus VISION_FRONTEND_IP_Reg_SelfTest(void * baseaddr_p);

#endif // VISION_FRONTEND_IP_H
