//////////////////////////////////////////////////////////////////////////////////
// Module Name : ip_fe_slave_lite_v1_0_S00_AXI
// Project     : Vision Front-End (Zynq-7020 / Zybo Z7-20)
//
// Description :
//   AXI4-Lite register bank. Generated by the Vivado "Create a new AXI4
//   peripheral" wizard and then edited to carry the Front-End register map.
//   This is the LIVE slave - it is the only thing answering on s00_axi.
//
//   Register map is docs/extractor_handoff_spec.md section 6:
//
//     slv_reg0  0x00  CTRL       [0] enable  [1] soft_reset  [2] frame_release
//                                [3] fb_inv  [4] stat_clear (W1S, reads 0)
//     slv_reg1  0x04  FE_MODE    [5:0]
//     slv_reg2  0x08  THRESH     [7:0] thresh   [15:8] c
//     slv_reg3  0x0C  GEOM       [11:0] width   [27:16] height
//     slv_reg4  0x10  STATUS     RO
//     slv_reg5  0x14  FRAME_CNT  RO
//     slv_reg6  0x18  FE_META    RO
//     slv_reg7  0x1C  IP_VERSION RO
//
// What was changed from the generated template, and why
//
//   1. Reset values. The template resets every register to 0. FE_MODE = 0 is an
//      R1 violation, so the design would come out of reset already asserting
//      cfg_invalid. Defaults are now the documented bring-up configuration.
//
//   2. slv_reg4..7 are read only. The template makes all eight registers RW.
//      Writing STATUS or FRAME_CNT has to do nothing, and reads have to return
//      the live status inputs rather than whatever was last written.
//
//   3. stat_clear is a one cycle strobe. The template would leave CTRL[4] set
//      as an ordinary RW bit, and software that wrote 1 and forgot would leave
//      the design permanently unable to latch a sticky event. The bit now
//      always reads back 0.
//
//   4. Writes are gated with axi_wready. The template writes on S_AXI_WVALID
//      alone, so a master holding WVALID across several cycles writes the same
//      register repeatedly. For plain config registers that is harmless, but it
//      stretches the stat_clear strobe past one cycle, which is exactly the
//      thing item 3 exists to prevent.
//
//   Everything else is the generated code, including the byte strobe handling
//   in the write path - that part the template already got right.
//
// NOTE: This file is intentionally ASCII-only.
//////////////////////////////////////////////////////////////////////////////////


`timescale 1 ns / 1 ps

	module ip_fe_slave_lite_v1_0_S00_AXI #
	(
		// Users to add parameters here

		// User parameters ends
		// Do not modify the parameters beyond this line

		// Width of S_AXI data bus
		parameter integer C_S_AXI_DATA_WIDTH	= 32,
		// Width of S_AXI address bus
		parameter integer C_S_AXI_ADDR_WIDTH	= 5
	)
	(
		// Users to add ports here

		// User ports ends
		// Do not modify the ports beyond this line

		// Global Clock Signal
		input wire  S_AXI_ACLK,
		// Global Reset Signal. This Signal is Active LOW
		input wire  S_AXI_ARESETN,
		// Write address (issued by master, acceped by Slave)
		input wire [C_S_AXI_ADDR_WIDTH-1 : 0] S_AXI_AWADDR,
		// Write channel Protection type. This signal indicates the
    		// privilege and security level of the transaction, and whether
    		// the transaction is a data access or an instruction access.
		input wire [2 : 0] S_AXI_AWPROT,
		// Write address valid. This signal indicates that the master signaling
    		// valid write address and control information.
		input wire  S_AXI_AWVALID,
		// Write address ready. This signal indicates that the slave is ready
    		// to accept an address and associated control signals.
		output wire  S_AXI_AWREADY,
		// Write data (issued by master, acceped by Slave) 
		input wire [C_S_AXI_DATA_WIDTH-1 : 0] S_AXI_WDATA,
		// Write strobes. This signal indicates which byte lanes hold
    		// valid data. There is one write strobe bit for each eight
    		// bits of the write data bus.    
		input wire [(C_S_AXI_DATA_WIDTH/8)-1 : 0] S_AXI_WSTRB,
		// Write valid. This signal indicates that valid write
    		// data and strobes are available.
		input wire  S_AXI_WVALID,
		// Write ready. This signal indicates that the slave
    		// can accept the write data.
		output wire  S_AXI_WREADY,
		// Write response. This signal indicates the status
    		// of the write transaction.
		output wire [1 : 0] S_AXI_BRESP,
		// Write response valid. This signal indicates that the channel
    		// is signaling a valid write response.
		output wire  S_AXI_BVALID,
		// Response ready. This signal indicates that the master
    		// can accept a write response.
		input wire  S_AXI_BREADY,
		// Read address (issued by master, acceped by Slave)
		input wire [C_S_AXI_ADDR_WIDTH-1 : 0] S_AXI_ARADDR,
		// Protection type. This signal indicates the privilege
    		// and security level of the transaction, and whether the
    		// transaction is a data access or an instruction access.
		input wire [2 : 0] S_AXI_ARPROT,
		// Read address valid. This signal indicates that the channel
    		// is signaling valid read address and control information.
		input wire  S_AXI_ARVALID,
		// Read address ready. This signal indicates that the slave is
    		// ready to accept an address and associated control signals.
		output wire  S_AXI_ARREADY,
		// Read data (issued by slave)
		output wire [C_S_AXI_DATA_WIDTH-1 : 0] S_AXI_RDATA,
		// Read response. This signal indicates the status of the
    		// read transfer.
		output wire [1 : 0] S_AXI_RRESP,
		// Read valid. This signal indicates that the channel is
    		// signaling the required read data.
		output wire  S_AXI_RVALID,
		// Read ready. This signal indicates that the master can
    		// accept the read data and response information.
		input wire  S_AXI_RREADY,

		// ---- to the Front-End ------------------------------------------
		output wire        cfg_enable,
		output wire        cfg_soft_reset,
		output wire        cfg_frame_release,   // OR with the PL signal outside
		output wire        cfg_fb_inv,
		output reg         cfg_stat_clear,      // one cycle strobe
		output wire [5:0]  cfg_fe_mode,
		output wire [7:0]  cfg_thresh,
		output wire [7:0]  cfg_c,
		output wire [11:0] cfg_width,
		output wire [11:0] cfg_height,

		// ---- from the Front-End ----------------------------------------
		input wire         sts_busy,
		input wire         sts_frame_ready,
		input wire         sts_frame_dropped,
		input wire         sts_cfg_invalid,
		input wire         sts_dma_overflow,
		input wire         sts_frame_stuck,
		input wire [15:0]  sts_frame_num,
		input wire [15:0]  sts_frame_drop_cnt,
		input wire [5:0]   sts_mode_applied,
		input wire [7:0]   sts_valid_margin
	);

	// AXI4LITE signals
	reg [C_S_AXI_ADDR_WIDTH-1 : 0] 	axi_awaddr;
	reg  	axi_awready;
	reg  	axi_wready;
	reg [1 : 0] 	axi_bresp;
	reg  	axi_bvalid;
	reg [C_S_AXI_ADDR_WIDTH-1 : 0] 	axi_araddr;
	reg  	axi_arready;
	reg [1 : 0] 	axi_rresp;
	reg  	axi_rvalid;

	// Example-specific design signals
	// local parameter for addressing 32 bit / 64 bit C_S_AXI_DATA_WIDTH
	// ADDR_LSB is used for addressing 32/64 bit registers/memories
	// ADDR_LSB = 2 for 32 bits (n downto 2)
	// ADDR_LSB = 3 for 64 bits (n downto 3)
	localparam integer ADDR_LSB = (C_S_AXI_DATA_WIDTH/32) + 1;
	localparam integer OPT_MEM_ADDR_BITS = 2;
	//----------------------------------------------
	//-- Signals for user logic register space example
	//------------------------------------------------
	//-- Number of Slave Registers 8
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg0;
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg1;
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg2;
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg3;
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg4;
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg5;
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg6;
	reg [C_S_AXI_DATA_WIDTH-1:0]	slv_reg7;
	integer	 byte_index;

	// I/O Connections assignments

	assign S_AXI_AWREADY	= axi_awready;
	assign S_AXI_WREADY	= axi_wready;
	assign S_AXI_BRESP	= axi_bresp;
	assign S_AXI_BVALID	= axi_bvalid;
	assign S_AXI_ARREADY	= axi_arready;
	assign S_AXI_RRESP	= axi_rresp;
	assign S_AXI_RVALID	= axi_rvalid;
	 //state machine varibles 
	 reg [1:0] state_write;
	 reg [1:0] state_read;
	 //State machine local parameters
	 localparam Idle = 2'b00,Raddr = 2'b10,Rdata = 2'b11 ,Waddr = 2'b10,Wdata = 2'b11;
	// Implement Write state machine
	// Outstanding write transactions are not supported by the slave i.e., master should assert bready to receive response on or before it starts sending the new transaction
	always @(posedge S_AXI_ACLK)                                 
	  begin                                 
	     if (S_AXI_ARESETN == 1'b0)                                 
	       begin                                 
	         axi_awready <= 0;                                 
	         axi_wready <= 0;                                 
	         axi_bvalid <= 0;                                 
	         axi_bresp <= 0;                                 
	         axi_awaddr <= 0;                                 
	         state_write <= Idle;                                 
	       end                                 
	     else                                  
	       begin                                 
	         case(state_write)                                 
	           Idle:                                      
	             begin                                 
	               if(S_AXI_ARESETN == 1'b1)                                  
	                 begin                                 
	                   axi_awready <= 1'b1;                                 
	                   axi_wready <= 1'b1;                                 
	                   state_write <= Waddr;                                 
	                 end                                 
	               else state_write <= state_write;                                 
	             end                                 
	           Waddr:        //At this state, slave is ready to receive address along with corresponding control signals and first data packet. Response valid is also handled at this state                                 
	             begin                                 
	               if (S_AXI_AWVALID && S_AXI_AWREADY)                                 
	                  begin                                 
	                    axi_awaddr <= S_AXI_AWADDR;                                 
	                    if(S_AXI_WVALID)                                  
	                      begin                                   
	                        axi_awready <= 1'b1;                                 
	                        state_write <= Waddr;                                 
	                        axi_bvalid <= 1'b1;                                 
	                      end                                 
	                    else                                  
	                      begin                                 
	                        axi_awready <= 1'b0;                                 
	                        state_write <= Wdata;                                 
	                        if (S_AXI_BREADY && axi_bvalid) axi_bvalid <= 1'b0;                                 
	                      end                                 
	                  end                                 
	               else                                  
	                  begin                                 
	                    state_write <= state_write;                                 
	                    if (S_AXI_BREADY && axi_bvalid) axi_bvalid <= 1'b0;                                 
	                   end                                 
	             end                                 
	          Wdata:        //At this state, slave is ready to receive the data packets until the number of transfers is equal to burst length                                 
	             begin                                 
	               if (S_AXI_WVALID)                                 
	                 begin                                 
	                   state_write <= Waddr;                                 
	                   axi_bvalid <= 1'b1;                                 
	                   axi_awready <= 1'b1;                                 
	                 end                                 
	                else                                  
	                 begin                                 
	                   state_write <= state_write;                                 
	                   if (S_AXI_BREADY && axi_bvalid) axi_bvalid <= 1'b0;                                 
	                 end                                              
	             end                                 
	          endcase                                 
	        end                                 
	      end                                 

	// Implement memory mapped register select and write logic generation
	// The write data is accepted and written to memory mapped registers when
	// axi_awready, S_AXI_WVALID, axi_wready and S_AXI_WVALID are asserted. Write strobes are used to
	// select byte enables of slave registers while writing.
	// These registers are cleared when reset (active low) is applied.
	// Slave register write enable is asserted when valid address and data are available
	// and the slave is ready to accept the write address and write data.
	 

	always @( posedge S_AXI_ACLK )
	begin
	  if ( S_AXI_ARESETN == 1'b0 )
	    begin
	      // Bring-up defaults, not zero. FE_MODE 0 violates R1.
	      slv_reg0 <= 32'h0000_0008;   // fb_inv = 1, enable = 0
	      slv_reg1 <= 32'h0000_0004;   // FE_MODE = P3 RAW
	      slv_reg2 <= 32'h0000_0580;   // c = 5, thresh = 128
	      slv_reg3 <= 32'h01E0_0280;   // height = 480, width = 640
	      slv_reg4 <= 0;
	      slv_reg5 <= 0;
	      slv_reg6 <= 0;
	      slv_reg7 <= 0;
	      cfg_stat_clear <= 1'b0;
	    end 
	  else begin
	    // A strobe, so it falls on its own the cycle after the write.
	    cfg_stat_clear <= 1'b0;

	    // axi_wready, not S_AXI_WVALID alone - see item 4 in the header.
	    if (S_AXI_WVALID && axi_wready)
	      begin
	        case ( (S_AXI_AWVALID) ? S_AXI_AWADDR[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB] : axi_awaddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB] )
	          3'h0: begin
	            for ( byte_index = 0; byte_index <= (C_S_AXI_DATA_WIDTH/8)-1; byte_index = byte_index+1 )
	              if ( S_AXI_WSTRB[byte_index] == 1 ) begin
	                // Respective byte enables are asserted as per write strobes 
	                // Slave register 0
	                slv_reg0[(byte_index*8) +: 8] <= S_AXI_WDATA[(byte_index*8) +: 8];
	              end  
	            // CTRL[4] is write-1-to-strobe, not a stored bit.
	            if ( S_AXI_WSTRB[0] == 1 ) cfg_stat_clear <= S_AXI_WDATA[4];
	          end
	          3'h1:
	            for ( byte_index = 0; byte_index <= (C_S_AXI_DATA_WIDTH/8)-1; byte_index = byte_index+1 )
	              if ( S_AXI_WSTRB[byte_index] == 1 ) begin
	                // Respective byte enables are asserted as per write strobes 
	                // Slave register 1
	                slv_reg1[(byte_index*8) +: 8] <= S_AXI_WDATA[(byte_index*8) +: 8];
	              end  
	          3'h2:
	            for ( byte_index = 0; byte_index <= (C_S_AXI_DATA_WIDTH/8)-1; byte_index = byte_index+1 )
	              if ( S_AXI_WSTRB[byte_index] == 1 ) begin
	                // Respective byte enables are asserted as per write strobes 
	                // Slave register 2
	                slv_reg2[(byte_index*8) +: 8] <= S_AXI_WDATA[(byte_index*8) +: 8];
	              end  
	          3'h3:
	            for ( byte_index = 0; byte_index <= (C_S_AXI_DATA_WIDTH/8)-1; byte_index = byte_index+1 )
	              if ( S_AXI_WSTRB[byte_index] == 1 ) begin
	                // Respective byte enables are asserted as per write strobes 
	                // Slave register 3
	                slv_reg3[(byte_index*8) +: 8] <= S_AXI_WDATA[(byte_index*8) +: 8];
	              end  

	          default : begin
	                      slv_reg0 <= slv_reg0;
	                      slv_reg1 <= slv_reg1;
	                      slv_reg2 <= slv_reg2;
	                      slv_reg3 <= slv_reg3;
	                      slv_reg4 <= slv_reg4;
	                      slv_reg5 <= slv_reg5;
	                      slv_reg6 <= slv_reg6;
	                      slv_reg7 <= slv_reg7;
	                    end
	        endcase
	      end

	    // Last statement wins, so this has to sit after the write block - it
	    // beats both the byte strobe loop and the default branch's
	    // slv_reg0 <= slv_reg0. CTRL[4] must always read back 0.
	    slv_reg0[4] <= 1'b0;
	  end
	end    

	// Implement read state machine
	  always @(posedge S_AXI_ACLK)                                       
	    begin                                       
	      if (S_AXI_ARESETN == 1'b0)                                       
	        begin                                       
	         //asserting initial values to all 0's during reset                                       
	         axi_arready <= 1'b0;                                       
	         axi_rvalid <= 1'b0;                                       
	         axi_rresp <= 1'b0;                                       
	         state_read <= Idle;                                       
	        end                                       
	      else                                       
	        begin                                       
	          case(state_read)                                       
	            Idle:     //Initial state inidicating reset is done and ready to receive read/write transactions                                       
	              begin                                                
	                if (S_AXI_ARESETN == 1'b1)                                        
	                  begin                                       
	                    state_read <= Raddr;                                       
	                    axi_arready <= 1'b1;                                       
	                  end                                       
	                else state_read <= state_read;                                       
	              end                                       
	            Raddr:        //At this state, slave is ready to receive address along with corresponding control signals                                       
	              begin                                       
	                if (S_AXI_ARVALID && S_AXI_ARREADY)                                       
	                  begin                                       
	                    state_read <= Rdata;                                       
	                    axi_araddr <= S_AXI_ARADDR;                                       
	                    axi_rvalid <= 1'b1;                                       
	                    axi_arready <= 1'b0;                                       
	                  end                                       
	                else state_read <= state_read;                                       
	              end                                       
	            Rdata:        //At this state, slave is ready to send the data packets until the number of transfers is equal to burst length                                       
	              begin                                           
	                if (S_AXI_RVALID && S_AXI_RREADY)                                       
	                  begin                                       
	                    axi_rvalid <= 1'b0;                                       
	                    axi_arready <= 1'b1;                                       
	                    state_read <= Raddr;                                       
	                  end                                       
	                else state_read <= state_read;                                       
	              end                                       
	           endcase                                       
	          end                                       
	        end                                         
	// Implement memory mapped register select and read logic generation
	  // Read mux. slv_reg4..6 return live Front-End status. slv_reg7 returns
	  // this IP's version. Camera and camera FIFO status are owned by the
	  // separate ov7670_axis AXI4-Lite peripheral.
	  //
	  // FE_META packs mode_applied and valid_margin at the bit positions the
	  // extraction side's Result Header Word 4 already uses, so software can
	  // mask the low 12 bits and copy them across. Framework document 6.3.
	  wire [2:0] rsel = axi_araddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB];
	  localparam [31:0] IP_VERSION = 32'h0001_0000;

	  assign S_AXI_RDATA =
	      (rsel == 3'h0) ? slv_reg0 :
	      (rsel == 3'h1) ? slv_reg1 :
	      (rsel == 3'h2) ? slv_reg2 :
	      (rsel == 3'h3) ? slv_reg3 :
	      (rsel == 3'h4) ? {25'd0, sts_frame_stuck, 1'b0,
	                        sts_dma_overflow, sts_cfg_invalid,
	                        sts_frame_dropped, sts_frame_ready, sts_busy} :
	      (rsel == 3'h5) ? {sts_frame_drop_cnt, sts_frame_num} :
	      (rsel == 3'h6) ? {16'd0,
	                        4'd0, sts_valid_margin[5:0], sts_mode_applied} :
	      (rsel == 3'h7) ? IP_VERSION :
	      32'd0;
	// ---- configuration out ------------------------------------------------
	assign cfg_enable        = slv_reg0[0];
	assign cfg_soft_reset    = slv_reg0[1];
	assign cfg_frame_release = slv_reg0[2];
	assign cfg_fb_inv        = slv_reg0[3];
	assign cfg_fe_mode       = slv_reg1[5:0];
	assign cfg_thresh        = slv_reg2[7:0];
	assign cfg_c             = slv_reg2[15:8];
	assign cfg_width         = slv_reg3[11:0];
	assign cfg_height        = slv_reg3[27:16];

	// Add user logic here

	// User logic ends

	endmodule
