#ifndef QR_HW_CONFIG_H
#define QR_HW_CONFIG_H

#include "xparameters.h"
#include "xil_types.h"

/* Current Exact-Sync XSA bindings generated by Vitis 2024.2. */
#ifndef XPAR_QR_RUNTIME_EXACT_0_BASEADDR
#error "XPAR_QR_RUNTIME_EXACT_0_BASEADDR is missing. Import the current Exact-Sync XSA."
#endif
#ifndef XPAR_AXI_DMA_0_BASEADDR
#error "XPAR_AXI_DMA_0_BASEADDR is missing."
#endif
#ifndef XPAR_AXI_DMA_IMAGE_BASEADDR
#error "XPAR_AXI_DMA_IMAGE_BASEADDR is missing."
#endif
#ifndef XPAR_XIICPS_0_BASEADDR
#error "XPAR_XIICPS_0_BASEADDR is missing."
#endif
#ifndef XPAR_VISION_FRONTEND_IP_0_BASEADDR
#error "XPAR_VISION_FRONTEND_IP_0_BASEADDR is missing."
#endif

#define QR_HW_RUNTIME_BASEADDR      ((UINTPTR)XPAR_QR_RUNTIME_EXACT_0_BASEADDR)
#define QR_HW_RESULT_DMA_BASEADDR   ((UINTPTR)XPAR_AXI_DMA_0_BASEADDR)
#define QR_HW_IMAGE_DMA_BASEADDR    ((UINTPTR)XPAR_AXI_DMA_IMAGE_BASEADDR)
#define QR_HW_I2C0_BASEADDR         ((UINTPTR)XPAR_XIICPS_0_BASEADDR)
#define QR_HW_FRONTEND_BASEADDR     ((UINTPTR)XPAR_VISION_FRONTEND_IP_0_BASEADDR)

#ifdef XPAR_AXI_VDMA_0_BASEADDR
#define QR_HW_VDMA_BASEADDR         ((UINTPTR)XPAR_AXI_VDMA_0_BASEADDR)
#endif
#ifdef XPAR_V_TC_0_BASEADDR
#define QR_HW_VTC_BASEADDR          ((UINTPTR)XPAR_V_TC_0_BASEADDR)
#endif
#ifdef XPAR_AXI_DYNCLK_0_BASEADDR
#define QR_HW_DYNCLK_BASEADDR       ((UINTPTR)XPAR_AXI_DYNCLK_0_BASEADDR)
#endif

#define QR_HW_IMAGE_WIDTH           640U
#define QR_HW_IMAGE_HEIGHT          480U
#define QR_HW_IMAGE_STRIDE          640U
#define QR_HW_IMAGE_BYTES           307200U
#define QR_HW_QRP1_MAX_WORDS        85U
#define QR_HW_QRP1_MAX_BYTES        340U

#define QR_HW_I2C_SCLK_HZ           50000U

/*
 * qr_perf PL: 62.5 MHz / 2 = 31.25 MHz XCLK. CLKRC bit7=0 keeps
 * PCLK <= XCLK/2; receiver has at least four PL cycles per PCLK period.
 * CLKRC=1 is the verified default. Override to 0 for the faster experimental
 * profile without rebuilding PL (more QR misses in the current indoor scene).
 */
#ifndef QR_CAMERA_CLKRC
#define QR_CAMERA_CLKRC 1U
#endif
#ifndef QR_CAMERA_SOURCE_SYNC
#define QR_CAMERA_SOURCE_SYNC 0
#endif
#if !QR_CAMERA_SOURCE_SYNC && (QR_CAMERA_CLKRC != 0 && QR_CAMERA_CLKRC != 1)
#error "Double-clock sensor profiles require stage3 source-synchronous CAM3 hardware."
#endif
#if QR_CAMERA_SOURCE_SYNC && (QR_CAMERA_CLKRC != 0 && QR_CAMERA_CLKRC != 1 && QR_CAMERA_CLKRC != 128 && QR_CAMERA_CLKRC != 129)
#error "Unsupported stage3 clock profile."
#endif
#define QR_HW_OV7670_CLKRC_BRINGUP   QR_CAMERA_CLKRC

/* Current preprocessing convention: black/foreground is represented as 1. */
#ifndef QR_HW_FRONTEND_FE_MODE
#define QR_HW_FRONTEND_FE_MODE       0x0000003DU
#endif
#define QR_HW_FRONTEND_FB_INVERT     1U
#define QR_HW_FRONTEND_PROGRAM_THRESH 0U
#define QR_HW_FRONTEND_THRESH         0x00000000U
#define QR_HW_FRONTEND_PROGRAM_GEOM   0U
#define QR_HW_FRONTEND_GEOM           0x00000000U

#endif
